version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '15.10'
    steps:
      - checkout
      - node/install-packages:
           app-dir: file-hosting-mern-stack/server/

      - run:
          command: npm run test
workflows:
  test_my_app:
    jobs:
      - test