version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '15.11'
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server/package.json
      - run:
          command: npm run start
workflows:
  test_my_app:
    jobs:
      - test